import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import QRCode from 'qrcode'
import { ArrowRight, Award, Check, ChevronLeft, ChevronRight, Clock3, Heart, Leaf, MapPin, Menu, Minus, Plus, QrCode, Quote, Search, ShieldCheck, Sparkles, Star, UtensilsCrossed, X } from 'lucide-react'
import './styles.css'

const categories = [
  { id: 'signature', label: 'Signature', icon: '✦' }, { id: 'starters', label: 'Starters', icon: '◈' },
  { id: 'veg', label: 'Pure Veg', icon: '❋' }, { id: 'nonveg', label: 'Non-Veg', icon: '♢' },
  { id: 'mains', label: 'Main Course', icon: '◉' }, { id: 'breads', label: 'Breads & Rice', icon: '⌁' },
  { id: 'desserts', label: 'Desserts', icon: '✧' }, { id: 'beverages', label: 'Beverages', icon: '○' },
]

const photos = [
  'https://images.unsplash.com/photo-1547592180-85f173990554', 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f',
  'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d', 'https://images.unsplash.com/photo-1559339352-11d035aa65de',
  'https://images.unsplash.com/photo-1527477396000-e27163b481c2', 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7',
  'https://images.unsplash.com/photo-1546833999-b9f581a1996d', 'https://images.unsplash.com/photo-1544025162-d76694265947',
  'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2', 'https://images.unsplash.com/photo-1476124369491-e7addf5db371',
  'https://images.unsplash.com/photo-1601050690597-df0568f70950', 'https://images.unsplash.com/photo-1563379091339-03246963d96c',
  'https://images.unsplash.com/photo-1551024506-0bccd828d307', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587',
  'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd', 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4',
].map(url => `${url}?auto=format&fit=crop&w=1000&q=88`)

const catalog = {
  signature: [['Truffle Cloud','Wild mushroom, parmesan foam, black truffle snow',890,'Chef’s pick'],['The Visionary Tasting','Seven courses through the chef’s imagination',3250,'Experience'],['Coastal Ember','Charcoal prawns, kokum, smoked coconut',1480,'New'],['Midnight Dahl','Black lentils, truffle butter, mini naan',690,'Bestseller'],['The Grand Roast','Garden vegetables, pepper jus, herb oil',1180,'Signature'],['Citrus Cured Salmon','Citrus, dill, avocado, salmon roe',1380,'Chef’s pick'],['Andhra Pepper Bird','Local chicken, roasted pepper, curry leaf',1180,'Local love'],['Forest & Fire','Wild mushrooms, clay oven, aged cheese',1020,'Vegetarian'],['Saffron Reef','Sea bass, saffron broth, coastal greens',1680,'Signature'],['Seven Seas Platter','Chef’s selection of Vizag’s finest seafood',2190,'To share']],
  starters: [['Avocado Caviar Toast','Sourdough, avocado, oscietra caviar, yuzu crème',760,'New'],['Tandoori Blue Prawn','Blue prawns, saffron marinade, coconut chutney',1280,''],['Korean Glazed Chicken','Crisp chicken, gochujang, sesame, spring onion',980,''],['Andhra Kodi Wings','Crisp wings, gongura glaze, toasted sesame',890,'Local love'],['Burrata & Mango','Creamy burrata, summer mango, basil oil',820,'Vegetarian'],['Crispy Lotus Stem','Chilli caramel, peanut, coriander, lime',620,''],['Pepper Calamari','Coastal squid, black pepper, curry leaf aioli',980,'Bestseller'],['Smoked Beet Tartare','Beetroot, caper, mustard, rye crisp',590,'Vegan'],['Lamb Galouti','Melt-in-mouth kebab, saffron roomali',1080,''],['Prawn Ghee Roast','Mangalorean masala, neer dosa crisp',1180,'Chef’s pick']],
  veg: [['Charcoal Paneer','Malai paneer, charcoal, makhani espuma, pickled onion',890,'Bestseller'],['Dal Visionary','24-hour black lentils, truffle butter, mini naan',650,''],['Wild Mushroom Risotto','Arborio rice, porcini, taleggio, forest herbs',1120,''],['Jackfruit Biryani','Aged basmati, jackfruit, saffron, crispy shallots',980,'Vegan'],['Bhutta & Burrata','Fire-roasted corn, burrata, chilli oil',760,'New'],['Kashmiri Dum Aloo','Baby potato, fennel, saffron, walnut',720,''],['Coconut Moilee','Seasonal vegetables, coastal coconut curry',790,'Vegan'],['Paneer Chettinad','Pepper masala, curry leaf, flaky paratha',850,'Spicy'],['Spinach Kofta','Silken spinach, cashew, tomato, saffron',820,''],['Konaseema Avakai','Local mango pickle, millet, smoked curd',690,'Local love']],
  nonveg: [['Kashmiri Lamb Shank','Slow-braised lamb, saffron jus, baby carrots',1680,'Signature'],['Malabar Sea Bass','Pan-seared sea bass, curry leaf beurre blanc',1580,''],['Nellore Crab Curry','Blue crab, coastal spices, appam',1480,'Local love'],['Peppercorn Tenderloin','Charred tenderloin, pepper jus, mash',2250,'Premium'],['Miso Black Cod','Miso, bok choy, ginger, sesame',1880,'Chef’s pick'],['Hyderabadi Gosht','Slow-cooked lamb, saffron, aged basmati',1480,''],['Tandoori Lobster','Half lobster, smoked butter, lemon',2480,'Experience'],['Chicken Xacuti','Goan roasted spices, coconut, poi bread',1120,''],['Seabass Koliwada','Crisp sea bass, kasundi, coastal slaw',1280,''],['Duck Pepper Fry','Crisp duck, Malabar pepper, parotta',1380,'New']],
  mains: [['Wild Mushroom Risotto','Arborio rice, porcini, taleggio, forest herbs',1120,''],['Andhra Coast Paella','Calasparra rice, prawns, mussels, local masala',1680,'Local love'],['Lamb Lasooni','Tender lamb, garlic jus, pomme purée',1580,''],['Coconut Curry Bowl','Seasonal vegetables, coconut, red rice',890,'Vegan'],['Truffle Ravioli','Ricotta, black truffle, sage brown butter',1320,'Bestseller'],['Seafood Moilee','Prawns, fish, coconut, turmeric, appam',1480,''],['Claypot Chicken','Herb rice, roast chicken, charred lemon',1180,''],['Miso Aubergine','Aubergine, sesame, soba, spring onion',860,'Vegan'],['Vizag Fish Thali','Today’s catch, dal, rice, pickle, 3 sides',1290,'Local love'],['The Green Plate','Grains, greens, hummus, fermented vegetables',820,'Healthy']],
  breads: [['Truffle & Garlic Naan','Clay oven naan, confit garlic, truffle oil',390,''],['Saffron Biryani','Aged basmati, saffron, crispy shallots, raita',980,''],['Roomali Roti Stack','Paper-thin breads, smoked butter, sea salt',260,''],['Cheese Kulcha','Mature cheddar, green chilli, onion, pickle',420,'Bestseller'],['Andhra Ghee Rice','Basmati, ghee, cashew, fried curry leaf',520,'Local love'],['Peshawari Naan','Dried fruit, nuts, rose, cardamom',420,''],['Millet Roti','Barnyard millet, sesame, cultured butter',300,'Healthy'],['Coastal Appam','Lacy rice pancake, coconut milk',340,''],['Laccha Paratha','Flaky layers, black salt, cultured butter',280,''],['Burnt Onion Pulao','Aged rice, caramelised onion, herbs',480,'']],
  desserts: [['Miso Caramel Sphere','Dark chocolate, miso caramel, sesame praline',590,'Must try'],['Rasmalai Tres Leches','Saffron milk cake, pistachio, rose petal',490,''],['Mango Yuzu Cloud','Alphonso, yuzu, coconut snow',520,'Seasonal'],['Burnt Basque Cheesecake','Vanilla, berry compote, sea salt',560,'Bestseller'],['Chocolate Forest','Cocoa soil, brownie, mousse, forest berries',620,''],['Tender Coconut Panna Cotta','Tender coconut, palm jaggery, lime',460,'Vegan'],['Gulkand Kulfi','Rose preserve, pistachio, falooda crunch',420,'Local love'],['Coffee Opera','Single-origin coffee, dark chocolate, hazelnut',580,''],['Pistachio Baklava','Layered pastry, saffron syrup, clotted cream',510,''],['Petit Four Flight','Four little sweets from our pastry studio',720,'To share']],
  beverages: [['Neon Garden','Yuzu, elderflower, cucumber, tonic, edible shimmer',490,'Zero proof'],['Vizag Sunset','Passion fruit, kokum, citrus, sparkling tea',420,'Signature'],['Hibiscus Highball','Hibiscus, ginger, lime, botanical soda',390,'Zero proof'],['Filter Coffee 2.0','Cold drip, jaggery, vanilla, cloud foam',360,'Local love'],['Mango Saffron Lassi','Alphonso, saffron, cultured yoghurt',390,'Bestseller'],['The Green Signal','Kiwi, basil, green apple, soda',420,'Healthy'],['Smoked Old Fashioned','Bourbon, jaggery, bitters, orange smoke',760,'Premium'],['Coastal Gin Tonic','Gin, kokum, pepper, tonic, botanicals',680,'Signature'],['Dark Chocolate Mocha','Cacao, espresso, oat milk, sea salt',420,''],['Tea Ceremony','Three rare Indian teas, petit fours',550,'Experience']],
}

const menuItems = Object.entries(catalog).flatMap(([category, list], categoryIndex) => list.map((item, itemIndex) => ({ id: `${category}-${itemIndex}`, category, name: item[0], description: item[1], price: item[2], tag: item[3], type: ['nonveg'].includes(category) || (category === 'starters' && [1,2,6,8,9].includes(itemIndex)) || (category === 'mains' && [1,2,5,6,8].includes(itemIndex)) ? 'nonveg' : 'veg', gallery: [0,1,2].map(offset => photos[(categoryIndex * 2 + itemIndex + offset) % photos.length]) })))
const reviews = [['Ananya Rao','Bengaluru','The QR menu feels like a tiny digital magazine. The food, the service, the view — all extraordinary.','5.0'],['Rohan Mehta','Mumbai','The Andhra Coast Paella and mango cloud were unforgettable. A truly modern Indian hospitality experience.','4.9'],['Meera & Kabir','Hyderabad','Every detail feels considered, from the animated menu to the beautiful plating. We are already planning our next stay.','5.0']]
const stories = [['A table facing the Bay','Inside the quiet ritual of our sunset dining room.','https://images.unsplash.com/photo-1517248135467-4c7edcad34c4'],['From coast to course','Meet the fishermen, farmers and makers behind Vizag’s new table.','https://images.unsplash.com/photo-1504674900247-0877df9cc836'],['The art of a slow morning','A 5-star breakfast, designed around the rhythm of the sea.','https://images.unsplash.com/photo-1533089860892-a7c6f0a88666'],['Night bloom at The Atrium','When our cocktail garden turns electric after dark.','https://images.unsplash.com/photo-1515003197210-e0cd71810b5f']]
function money(value) { return `₹${value.toLocaleString('en-IN')}` }
function Gallery({ item }) { const [index, setIndex] = useState(0); useEffect(() => { const timer = setInterval(() => setIndex(current => (current + 1) % 3), 4200); return () => clearInterval(timer) }, [item.id]); return <div className="food-image gallery"><img src={item.gallery[index]} alt={`${item.name} presentation ${index + 1}`} /><button className="gallery-arrow left" aria-label="Previous image" onClick={() => setIndex((index + 2) % 3)}><ChevronLeft size={15} /></button><button className="gallery-arrow right" aria-label="Next image" onClick={() => setIndex((index + 1) % 3)}><ChevronRight size={15} /></button><div className="gallery-dots">{item.gallery.map((_, dot) => <button key={dot} aria-label={`Show image ${dot + 1}`} onClick={() => setIndex(dot)} className={dot === index ? 'current' : ''}></button>)}</div><span className={`diet-dot ${item.type}`}></span>{item.tag && <span className="item-tag">{item.tag}</span>}</div> }
function QRPanel() { const [dataUrl, setDataUrl] = useState(''); const menuUrl = `${window.location.origin}${window.location.pathname.split('#')[0]}#menu`; useEffect(() => { QRCode.toDataURL(menuUrl, { width: 240, margin: 1, color: { dark: '#071111', light: '#f0e9da' } }).then(setDataUrl) }, [menuUrl]); return <aside className="qr-panel"><div className="qr-heading"><span className="eyebrow">TABLE EXPERIENCE</span><QrCode size={18} /></div><h3>Scan. Sit back.<br /><em>Stay curious.</em></h3><p>Point your camera here to open the VisionariesAI digital menu.</p>{dataUrl && <img className="qr-image" src={dataUrl} alt="QR code for VisionariesAI Hotel menu" />}<div className="qr-url"><span>{menuUrl.replace(/^https?:\/\//, '')}</span><Check size={14} /></div><small>Menu updates live · No app required</small></aside> }
function CartDrawer({ items, onClose, add, remove, subtotal }) {
  const service = Math.round(subtotal * 0.05), tax = Math.round((subtotal + service) * 0.05), total = subtotal + service + tax
  return <div className="cart-layer" onClick={onClose}><aside className="cart-drawer" onClick={e => e.stopPropagation()}><div className="cart-drawer-head"><div><span className="eyebrow">YOUR TABLE · LIVE ORDER</span><h2>Good choices.</h2><p>{items.length ? `${items.reduce((sum, item) => sum + item.quantity, 0)} items selected` : 'Your table is ready when you are.'}</p></div><button className="drawer-close" onClick={onClose} aria-label="Close cart"><X size={19} /></button></div>{items.length ? <><div className="cart-items">{items.map(({ item, quantity }) => <div className="cart-item" key={item.id}><img src={item.gallery[0]} alt={item.name} /><div className="cart-item-main"><strong>{item.name}</strong><span>{money(item.price)} each</span><div className="cart-quantity"><button onClick={() => remove(item.id)}><Minus size={13} /></button><b>{quantity}</b><button onClick={() => add(item.id)}><Plus size={13} /></button></div></div><strong className="cart-line-total">{money(item.price * quantity)}</strong></div>)}</div><div className="cart-summary"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Service · 5%</span><b>{money(service)}</b></div><div><span>Taxes · 5%</span><b>{money(tax)}</b></div><div className="cart-total"><span>Estimated total</span><strong>{money(total)}</strong></div><button className="request-button"><span>Request at my table</span><ArrowRight size={17} /></button><small>Payment is completed at the hotel · No commitment yet</small></div></> : <div className="empty-cart"><div className="empty-cart-icon"><UtensilsCrossed size={25} /></div><h3>Your table is waiting.</h3><p>Add a dish from the menu and it will appear here with live quantities and pricing.</p><button className="request-button" onClick={onClose}>Explore the menu <ArrowRight size={17} /></button></div>}</aside></div>
}

function ReviewsPage() { return <section className="subpage dark-page reviews-page"><div className="subpage-head"><span className="eyebrow">THE GUESTBOOK · 4.9 / 5</span><h2>Stories from<br /><em>the table.</em></h2><p>Real moments from guests who came for dinner and left with a new favourite place.</p></div><div className="review-grid">{reviews.map(([name, place, text, score]) => <article className="review-card" key={name}><Quote size={25} /><div className="stars">{[1,2,3,4,5].map(i => <Star key={i} size={13} fill="currentColor" />)}</div><p>“{text}”</p><footer><strong>{name}</strong><span>{place} · {score}</span></footer></article>)}</div><div className="review-stat"><span><strong>12,840+</strong> guests hosted</span><span><strong>98%</strong> would return</span><span><strong>24</strong> countries at our table</span></div></section> }
function StoriesPage() { return <section className="subpage stories-page"><div className="subpage-head"><span className="eyebrow">THE JOURNAL · VISIONARIESAI</span><h2>Inside the<br /><em>experience.</em></h2><p>Notes, images and ingredients from our coast-facing world in Visakhapatnam.</p></div><div className="story-grid">{stories.map(([title, text, image], index) => <article className={`story-card story-${index}`} key={title}><img src={`${image}?auto=format&fit=crop&w=1200&q=88`} alt={title} /><div className="story-overlay"><span>0{index + 1} · JOURNAL</span><h3>{title}</h3><p>{text}</p><button>Read story <ArrowRight size={15} /></button></div></article>)}</div></section> }
function TrustSection() { return <section className="trust-section"><div><span className="eyebrow">THE VISIONARIES STANDARD</span><h2>Crafted with<br /><em>care.</em></h2></div><div className="trust-copy"><p>Our promise is simple: source beautifully, serve thoughtfully, and leave every place a little better than we found it.</p><div className="cert-grid"><span><ShieldCheck size={21} /><strong>FSSAI<br /><small>Certified kitchen</small></strong></span><span><Award size={21} /><strong>ISO 22000<br /><small>Food safety system</small></strong></span><span><Leaf size={21} /><strong>GREEN KEY<br /><small>Sustainable stay</small></strong></span><span><Heart size={21} /><strong>LOCAL FIRST<br /><small>Coastal producers</small></strong></span></div></div></section> }

function App() {
  const [activeCategory, setActiveCategory] = useState('signature'), [diet, setDiet] = useState('all'), [search, setSearch] = useState(''), [cart, setCart] = useState({}), [showQR, setShowQR] = useState(false), [showCart, setShowCart] = useState(false), [mobileNav, setMobileNav] = useState(false), [view, setView] = useState(() => window.location.hash === '#menu' || window.location.pathname.endsWith('/menu') ? 'menu' : 'home'), [addedId, setAddedId] = useState(null)
  const filteredItems = useMemo(() => menuItems.filter(item => item.category === activeCategory && (diet === 'all' || item.type === diet) && (`${item.name} ${item.description}`.toLowerCase().includes(search.toLowerCase()))), [activeCategory, diet, search])
  const cartCount = Object.values(cart).reduce((a, b) => a + b, 0), cartItems = Object.entries(cart).filter(([, quantity]) => quantity > 0).map(([id, quantity]) => ({ item: menuItems.find(item => item.id === id), quantity })), subtotal = cartItems.reduce((sum, entry) => sum + entry.item.price * entry.quantity, 0)
  const add = id => { setCart(c => ({ ...c, [id]: (c[id] || 0) + 1 })); setAddedId(id); setTimeout(() => setAddedId(current => current === id ? null : current), 700) }
  const remove = id => setCart(c => ({ ...c, [id]: Math.max(0, (c[id] || 0) - 1) }))
  const go = next => { setView(next); setMobileNav(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  return <div className="app-shell"><header className="topbar"><button className="brand brand-button" onClick={() => go('home')}><span className="brand-mark">V</span><div><strong>VISIONARIES<span>AI</span></strong><small>HOTEL · VISAKHAPATNAM</small></div></button><nav className={mobileNav ? 'nav open' : 'nav'}><button className={view === 'home' ? 'active' : ''} onClick={() => go('home')}>Home</button><button className={view === 'menu' ? 'active' : ''} onClick={() => go('menu')}>Menu</button><button className={view === 'reviews' ? 'active' : ''} onClick={() => go('reviews')}>Reviews</button><button className={view === 'stories' ? 'active' : ''} onClick={() => go('stories')}>Stories</button></nav><div className="top-actions"><button className="icon-button" onClick={() => setShowQR(true)} aria-label="Show QR"><QrCode size={19} /></button><button className={`cart-button ${cartCount ? 'has-items' : ''}`} onClick={() => setShowCart(true)}><UtensilsCrossed size={17} /><span>{cartCount ? `${cartCount} items · ${money(subtotal)}` : 'Your table'}</span>{cartCount > 0 && <b className="cart-badge">{cartCount}</b>}</button><button className="menu-toggle" onClick={() => setMobileNav(!mobileNav)}>{mobileNav ? <X /> : <Menu />}</button></div></header>
    {view === 'home' && <main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="pulse"></span> A NEW ERA OF DINING · OPEN 24 HOURS</div><h1>Eat beyond<br /><em>expectation.</em></h1><p>Where inventive coastal cuisine meets quiet luxury. A digital menu curated for the endlessly curious.</p><div className="hero-meta"><span><MapPin size={16} /> The Grand Atrium, Visakhapatnam</span><span><Clock3 size={16} /> 12:00 PM — 01:00 AM</span></div><button className="primary-cta" onClick={() => go('menu')}>Explore the menu <ArrowRight size={18} /></button></div><div className="hero-visual"><div className="visual-glow"></div><img src={photos[15]} alt="Futuristic luxury restaurant interior" /><div className="floating-note"><Sparkles size={16} /><span><strong>Tonight’s mood</strong><br />Unexpectedly delicious</span></div><div className="rating"><Star size={15} fill="currentColor" /> 4.9 <span>Guest rated</span></div></div></section><section className="promo-strip"><div><span className="promo-kicker">LIMITED TIME · 15 SEP — 30 SEP</span><strong>Arrive hungry. Leave <em>inspired.</em></strong></div><p>Complimentary signature dessert for all dinner reservations.</p><button onClick={() => go('menu')}>Claim the moment <ArrowRight size={16} /></button></section><section className="home-preview"><div><span className="eyebrow">DESIGNED FOR THE CURIOUS</span><h2>More than a menu.<br /><em>A point of view.</em></h2></div><div className="preview-cards"><button onClick={() => go('reviews')}><span>01 · THE GUESTBOOK</span><strong>See what guests<br />are saying <ArrowRight size={17} /></strong></button><button onClick={() => go('stories')}><span>02 · THE JOURNAL</span><strong>Explore our<br />visual stories <ArrowRight size={17} /></strong></button></div></section><TrustSection /></main>}
    {view === 'menu' && <main><section className="menu-section menu-page" id="menu"><div className="section-intro"><div><span className="eyebrow">THE EDITED MENU · VISAKHAPATNAM</span><h2>Made for your <em>next story.</em></h2><p className="intro-note">80 dishes · 8 collections · infinite possibilities</p></div><div className="search-box"><Search size={17} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search the menu" /></div></div><div className="menu-controls"><div className="category-scroll">{categories.map(cat => <button key={cat.id} className={activeCategory === cat.id ? 'selected' : ''} onClick={() => setActiveCategory(cat.id)}><span>{cat.icon}</span>{cat.label}</button>)}</div><div className="diet-toggle"><button className={diet === 'all' ? 'selected' : ''} onClick={() => setDiet('all')}>All</button><button className={diet === 'veg' ? 'selected veg' : ''} onClick={() => setDiet('veg')}><Leaf size={13} /> Veg</button><button className={diet === 'nonveg' ? 'selected nonveg' : ''} onClick={() => setDiet('nonveg')}>◆ Non-veg</button></div></div><div className="category-title"><div><span className="eyebrow">{categories.find(x => x.id === activeCategory)?.label.toUpperCase()}</span><h3>{activeCategory === 'signature' ? 'Our signatures' : categories.find(x => x.id === activeCategory)?.label}</h3></div><span className="item-count">{filteredItems.length} selections</span></div><div className="food-grid">{filteredItems.map(item => <article className="food-card" key={item.id}><Gallery item={item} /><div className="food-body"><div><h4>{item.name}</h4><p>{item.description}</p></div><div className="food-footer"><strong className="food-price"><small>FROM</small>{money(item.price)}</strong><div className="quantity">{cart[item.id] ? <><button onClick={() => remove(item.id)}><Minus size={14} /></button><span>{cart[item.id]}</span><button onClick={() => add(item.id)}><Plus size={14} /></button></> : <button className={`add-button ${addedId === item.id ? 'added' : ''}`} onClick={() => add(item.id)}>{addedId === item.id ? <><Check size={14} /> Added</> : <>Add to table <Plus size={14} /></>}</button>}</div></div></div></article>)}</div>{!filteredItems.length && <div className="empty-state">No dishes found. Try another category or search term.</div>}</section><TrustSection /></main>}
    {view === 'reviews' && <main><ReviewsPage /><TrustSection /></main>}{view === 'stories' && <main><StoriesPage /><TrustSection /></main>}
    <footer><button className="brand brand-button" onClick={() => go('home')}><span className="brand-mark">V</span><div><strong>VISIONARIES<span>AI</span></strong><small>HOTEL · VISAKHAPATNAM</small></div></button><p>Good food. Great stories. Your table is waiting.</p><span>© 2026 VisionariesAI Hospitality</span></footer>{showCart && <CartDrawer items={cartItems} onClose={() => setShowCart(false)} add={add} remove={remove} subtotal={subtotal} />}{showQR && <div className="modal-backdrop" onClick={() => setShowQR(false)}><div className="modal" onClick={e => e.stopPropagation()}><button className="close" onClick={() => setShowQR(false)}><X /></button><QRPanel /></div></div>}
  </div>
}
createRoot(document.getElementById('root')).render(<App />)
